### ISSUE TITLE
Example of connection to aws cloud with ethernet shield encj2860

### ISSUE THREAD

**Issue by simogaspa84** [khoih-prog/MQTTPubSubClient_Generic#1]
Hi @khoih-prog 

thanks for your amazing work... 
I saw you uploaded an example of the connection with aws with wifi using your lib.
Do you think it is possible to upload the same example of connection to aws cloud with an ethernet shield encj2860 ?

Thanks a lot for your amazing work

**Comment by khoih-prog** [comment]
Hi @simogaspa84 

Thanks for your nice words.

As ENC28J60 using [**EthernetWebServer_SSL**](https://github.com/khoih-prog/EthernetWebServer_SSL) with [**EthernetENC library**](https://github.com/JAndrassy/EthernetENC) can do TLS/SSL, I don't think there is any unsolvable issue to modify [**WiFiMQTTSecureAWS**](https://github.com/khoih-prog/MQTTPubSubClient_Generic/tree/main/examples/WiFi/WiFiMQTTSecureAWS) to use **Ethernet** (W5x00, ENC28J60, etc.).

The problem now is that I don't have spare time to do this. We'd appreciate it if you can convert, test, then if OK, make a **PR** to benefit many other users.

**Comment by khoih-prog** [comment]
You can also try [**AWS_IoT** example](https://github.com/khoih-prog/EthernetWebServer_SSL/tree/main/examples/AWS_IoT) of [**EthernetWebServer_SSL** library](https://github.com/khoih-prog/EthernetWebServer_SSL)

**Comment by khoih-prog** [comment]
Either one is possible for me. I'm confident and close the issue.

**Comment by simogaspa84** [comment]
Ok @khoih-prog  I will try I am not an expert as you but I will try

**Comment by khoih-prog** [comment]
With your persistence and inquisitive mind, you'll be expert after a **short** while.
